name: Build and Distribute Wheel

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    - name: Install dependencies
      run: pip install cmake setuptools wheel

    - name: Build and package
      working-directory: ./jerry  # Set working directory to the subfolder
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ../..

    - name: Build wheel
      working-directory: ./jerry  # Set working directory to the subfolder
      run: python mac_setup.py bdist_wheel

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: ./jerry/dist/*.whl
