name: Build and Distribute Wheels

on:
  push:
    branches:
      - master  # Adjust the branch name if necessary

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    strategy:
      matrix:
        python-version: 3.X # Add or remove Python versions as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install cmake setuptools wheel
        pip install pybind11

    - name: Build and package
      working-directory: ./jerry  # Set working directory to the subfolder
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ../..

    - name: Build wheel
      working-directory: ./jerry  # Set working directory to the subfolder
      run: python setup.py bdist_wheel

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheel-py${{ matrix.python-version }}
        path: ./jerry/dist/*.whl
