name: Build and Distribute Wheel

on:
  push:
    branches:
      - master  # Adjust the branch name if necessary

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install cmake setuptools wheel
        pip install pybind11

    - name: Build and package
      working-directory: ./jerry  # Set working directory to the subfolder
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/pybind11 ..
        make
        cd ../..

    - name: Build wheel
      working-directory: ./jerry  # Set working directory to the subfolder
      run: python setup.py bdist_wheel

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheel-py3.10
        path: ./jerry/dist/*.whl
