name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.1.1

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      working-directory: jerry

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./jerry/wheelhouse/*.whl
